package schema

// AudioExts is the set of commonly used audio file extensions.
var AudioExts = map[string]bool{
	".mp3":  true,
	".flac": true,
	".ogg":  true,
	".opus": true,
	".wav":  true,
	".aac":  true,
	".m4a":  true,
	".m4b":  true,
	".wma":  true,
	".aiff": true,
	".aif":  true,
	".ape":  true,
	".mka":  true,
	".mp4":  true,
	".webm": true,
	".ra":   true,
	".rm":   true,
	".mid":  true,
	".midi": true,
	".amr":  true,
	".3gp":  true,
	".spx":  true,
	".tta":  true,
	".wv":   true,
	".dsf":  true,
	".dff":  true,
	".caf":  true,
	".au":   true,
	".snd":  true,
}
